export const RESOURCE_LINKS = [
  {
    id: "insurance",
    title: "Offered insurance options",
    stat: "5+ mainstream providers",
    description:
      "Compare third-party and comprehensive cover options before choosing a class pathway.",
    href: "https://www.aak.co.ke/insurance/",
    cta: "Explore insurance",
  },
  {
    id: "license-stats",
    title: "People with driver licenses",
    stat: "3M+ active drivers",
    description:
      "Use official NTSA publications to understand licensing trends and demand by vehicle class.",
    href: "https://ntsa.go.ke",
    cta: "View NTSA data",
  },
  {
    id: "vehicle-prices",
    title: "Average vehicle prices",
    stat: "KES 1.2M median used-car range",
    description:
      "Review current market pricing to estimate the vehicle budget for your selected class.",
    href: "https://www.cheki.co.ke/",
    cta: "Check market prices",
  },
];

export const CLASS_GROUPS = {
  a: {
    title: "Motorcycles and 3-Wheelers",
    icon: "A",
    bg: "from-green-50 to-emerald-100",
    classes: [
      {
        id: "a1",
        name: "A1 - Light Motorcycles",
        icon: "A1",
        image: "/classes/a1.jpg",
        desc: "Light motorcycles up to 125cc and 11kW. Ideal for beginners.",
        reqs: ["Age: 16+", "Engine: Up to 125cc", "Power: Max 11kW"],
      },
      {
        id: "a2",
        name: "A2 - Medium Motorcycles",
        icon: "A2",
        image: "/classes/a2.jpg",
        desc: "Motorcycles up to 35kW for stronger performance and longer trips.",
        reqs: ["Age: 18+", "Power: Max 35kW", "Ratio: 0.2kW/kg max"],
      },
      {
        id: "a3",
        name: "A3 - Three-Wheelers",
        icon: "A3",
        image: "/classes/a3.jpg",
        desc: "Tuk-tuks and tricycles for passenger and small-delivery transport.",
        reqs: ["Age: 18+", "Type: 3-wheeled", "Commercial use supported"],
      },
    ],
  },
  b: {
    title: "Light Vehicles",
    icon: "B",
    bg: "from-blue-50 to-indigo-100",
    classes: [
      {
        id: "b1",
        name: "B1 - Light Vehicles",
        icon: "B1",
        image: "/classes/b2.jpg",
        desc: "Personal vehicles up to 3,500kg and up to 8 passengers.",
        reqs: ["Age: 18+", "Weight: Up to 3,500kg", "Passengers: Up to 8"],
      },
      {
        id: "b2",
        name: "B2 - Light Commercial",
        icon: "B2",
        image: "/classes/b2.jpg",
        desc: "Vans and light commercial vehicles for business and logistics.",
        reqs: [
          "Age: 18+",
          "Type: Light commercial",
          "Commercial use supported",
        ],
      },
    ],
  },
  c: {
    title: "Trucks and Commercial",
    icon: "C",
    bg: "from-yellow-50 to-orange-100",
    classes: [
      {
        id: "c1",
        name: "C1 - Medium Trucks",
        icon: "C1",
        image: "/classes/c1.jpg",
        desc: "Trucks between 3,500kg and 16,000kg for mid-scale cargo work.",
        reqs: [
          "Age: 21+",
          "Weight: 3,500-16,000kg",
          "Prior experience required",
        ],
      },
      {
        id: "c2",
        name: "C2 - Heavy Trucks",
        icon: "C2",
        image: "/classes/c1.jpg",
        desc: "Heavy commercial vehicles over 16,000kg for long-haul operations.",
        reqs: ["Age: 21+", "Weight: Over 16,000kg", "C1 background required"],
      },
    ],
  },
  d: {
    title: "PSV and Buses",
    icon: "D",
    bg: "from-purple-50 to-indigo-100",
    classes: [
      {
        id: "d1",
        name: "D1 - PSV Minibuses",
        icon: "D1",
        image: "/classes/d1.jpg",
        desc: "PSV minibuses and matatus carrying 9-25 passengers.",
        reqs: ["Age: 21+", "Capacity: 9-25 passengers", "PSV badge required"],
      },
      {
        id: "d2",
        name: "D2 - Large Buses",
        icon: "D2",
        image: "/classes/d1.jpg",
        desc: "Large buses over 25 passengers for long-route passenger service.",
        reqs: [
          "Age: 21+",
          "Capacity: 25+ passengers",
          "D1 background required",
        ],
      },
    ],
  },
};

export const INDIVIDUAL_CLASSES = {
  a1: {
    title: "A1 - Light Motorcycles",
    subtitle: "Up to 125cc",
    color: "from-green-600 to-emerald-600",
    bg: "from-green-50 to-emerald-100",
    image: "/classes/a1.jpg",
    desc: "A1 allows you to ride light motorcycles with lower power output, ideal for early-stage riders and urban movement.",
    reqs: [
      "Minimum age: 16 years",
      "Engine capacity: Up to 125cc",
      "Power output: Maximum 11kW",
      "Valid medical certificate",
    ],
    ideal: ["City commuting", "First-time riders"],
  },
  a2: {
    title: "A2 - Medium Motorcycles",
    subtitle: "Up to 35kW",
    color: "from-blue-600 to-cyan-600",
    bg: "from-blue-50 to-cyan-100",
    image: "/classes/a2.jpg",
    desc: "A2 supports more powerful motorcycles, useful for highway riding and longer travel distances.",
    reqs: [
      "Minimum age: 18 years",
      "Power output: Maximum 35kW",
      "Power-to-weight ratio not exceeding 0.2kW/kg",
      "Valid medical certificate",
    ],
    ideal: ["Highway riding", "Long-distance travel"],
  },
  a3: {
    title: "A3 - Three-Wheelers",
    subtitle: "Tuk-tuks and tricycles",
    color: "from-purple-600 to-pink-600",
    bg: "from-purple-50 to-pink-100",
    image: "/classes/a3.jpg",
    desc: "A3 covers three-wheel transport used for both passenger and commercial delivery services.",
    reqs: [
      "Minimum age: 18 years",
      "Vehicle type: Three-wheeled motorcycles",
      "Commercial use permitted",
      "Valid medical certificate",
    ],
    ideal: ["Passenger transport", "Delivery operations"],
  },
  b1: {
    title: "B1 - Light Vehicles",
    subtitle: "Personal cars",
    color: "from-blue-600 to-indigo-600",
    bg: "from-blue-50 to-indigo-100",
    image: "/classes/b2.jpg",
    desc: "B1 is the core class for private driving, covering most personal and family vehicles.",
    reqs: [
      "Minimum age: 18 years",
      "Vehicle weight: Up to 3,500kg",
      "Passenger capacity: Up to 8 passengers",
      "Valid medical certificate",
    ],
    ideal: ["Personal mobility", "Family driving"],
  },
  b2: {
    title: "B2 - Light Commercial",
    subtitle: "Vans and light commercial",
    color: "from-cyan-600 to-blue-600",
    bg: "from-cyan-50 to-blue-100",
    image: "/classes/b2.jpg",
    desc: "B2 is suited to business owners and operators using light commercial vehicles daily.",
    reqs: [
      "Minimum age: 18 years",
      "Vehicle type: Light commercial",
      "Commercial use permitted",
      "Valid medical certificate",
    ],
    ideal: ["Small business", "Delivery services"],
  },
  c1: {
    title: "C1 - Medium Trucks",
    subtitle: "Commercial trucks",
    color: "from-yellow-600 to-orange-600",
    bg: "from-yellow-50 to-orange-100",
    image: "/classes/c1.jpg",
    desc: "C1 prepares drivers for medium freight vehicles in logistics and construction work.",
    reqs: [
      "Minimum age: 21 years",
      "Vehicle weight: 3,500kg - 16,000kg",
      "Commercial driving experience required",
      "Valid medical certificate",
    ],
    ideal: ["Construction logistics", "Regional freight transport"],
  },
  c2: {
    title: "C2 - Heavy Trucks",
    subtitle: "Heavy commercial",
    color: "from-orange-600 to-red-600",
    bg: "from-orange-50 to-red-100",
    image: "/classes/c1.jpg",
    desc: "C2 licenses support heavy-duty hauling for long-distance and high-capacity cargo routes.",
    reqs: [
      "Minimum age: 21 years",
      "Vehicle weight: Over 16,000kg",
      "C1 license experience required",
      "Valid medical certificate",
    ],
    ideal: ["Long-haul trucking", "Heavy industry transport"],
  },
  d1: {
    title: "D1 - PSV Minibuses",
    subtitle: "Matatus and small PSV",
    color: "from-purple-600 to-indigo-600",
    bg: "from-purple-50 to-indigo-100",
    image: "/classes/d1.jpg",
    desc: "D1 focuses on public-service minibus operations and structured passenger transport.",
    reqs: [
      "Minimum age: 21 years",
      "Passenger capacity: 9-25 passengers",
      "PSV badge required",
      "Valid medical certificate",
    ],
    ideal: ["Matatu operations", "School transport"],
  },
  d2: {
    title: "D2 - Large Buses",
    subtitle: "Coaches and large buses",
    color: "from-indigo-600 to-purple-600",
    bg: "from-indigo-50 to-purple-100",
    image: "/classes/d1.jpg",
    desc: "D2 covers high-capacity buses for intercity, corporate, and institutional passenger routes.",
    reqs: [
      "Minimum age: 21 years",
      "Passenger capacity: Over 25 passengers",
      "D1 license experience required",
      "Valid medical certificate",
    ],
    ideal: ["Long-distance buses", "Corporate transport"],
  },
};
